#!/bin/sh 

CLONE_DIR=bootstrap-downloader
if [ $# -lt 1 ]; then
  echo "usage: bootstrap dir [branch]"
  exit 1
fi
OUTPUT_DIR=$1
VERSION=$2
if [ "${VERSION}" == "" ]; then
  VERSION="2.2.1"
fi

if [ -d ${CLONE_DIR} ]; then
  mv ${CLONE_DIR} ${CLONE_DIR}_bk
fi

git clone git://github.com/seratch/bootstrap-downloader.git -b ${VERSION}
cd ${CLONE_DIR}
rm -rf .git
rm -rf README.md
rm -rf tools
cd - > /dev/null

if [ -d ${OUTPUT_DIR} ]; then
  cp -pr ${CLONE_DIR}/* ${OUTPUT_DIR}/.
  rm -rf ${CLONE_DIR}
else
   mv ${CLONE_DIR} ${OUTPUT_DIR}
fi

if [ -d ${CLONE_DIR} ]; then
  mv ${CLONE_DIR}_bk ${CLONE_DIR}
fi

echo ""
echo "Twitter Bootstrap ${VERSION} installed to ${OUTPUT_DIR}" 
echo ""

